### ISSUE TITLE
如何部署线上服务器？

### ISSUE THREAD

**Issue by Nebulazheng** [yi-ge/Koa2-API-Scaffold#17]
我使用你的这个尝试做来一个项目，本地环境已经正常跑通来，部署线上环境各种不对。node npm pm2 都装了  是直接允许pm2 start pm2.js吗？

**Comment by Nebulazheng** [comment]
# npm run dev

> koa2-api-scaffold@1.0.2 dev /www
> gulp

[14:25:42] Using gulpfile /www/gulpfile.js
[14:25:42] Starting 'default'...
[14:25:42] Starting 'ESlint'...
[14:25:42] 'ESlint' errored after 26 ms
[14:25:42] Error: Cannot read config file: /www/.eslintrc.js
Error: Cannot find module '/www/.eslintrc.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at resolveFileName (/www/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/www/node_modules/resolve-from/index.js:43:9)
    at module.exports (/www/node_modules/resolve-from/index.js:46:41)
    at module.exports.moduleId (/www/node_modules/import-fresh/index.js:13:19)
    at loadJSConfigFile (/www/node_modules/eslint/lib/cli-engine/config-array-factory.js:201:16)
    at loadConfigFile (/www/node_modules/eslint/lib/cli-engine/config-array-factory.js:284:20)
    at ConfigArrayFactory._loadConfigData (/www/node_modules/eslint/lib/cli-engine/config-array-factory.js:496:13)
    at ConfigArrayFactory.loadFile (/www/node_modules/eslint/lib/cli-engine/config-array-factory.js:416:18)
    at createCLIConfigArray (/www/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:157:35)
[14:25:42] 'default' errored after 29 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! koa2-api-scaffold@1.0.2 dev: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the koa2-api-scaffold@1.0.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-08T06_25_42_442Z-debug.log
[root@iZ8vb7ux6dyyb668fetshwZ www]#

**Comment by Nebulazheng** [comment]
`npm run start

> koa2-api-scaffold@1.0.2 start /www
> gulp nodemon

[14:26:47] Using gulpfile /www/gulpfile.js
[14:26:47] Starting 'nodemon'...
[14:26:48] [nodemon] 1.19.4
[14:26:48] [nodemon] to restart at any time, enter `rs`
[14:26:48] [nodemon] ignoring: build/*.js dist/*.js nodemon.json .git node_modules/**/node_modules gulpfile.js
[14:26:48] [nodemon] watching dir(s): *.*
[14:26:48] [nodemon] watching extensions: js,json
[14:26:48] [nodemon] starting `node build/dev-server.js`
[14:26:48] [nodemon] forking
[14:26:48] [nodemon] child pid: 26160
[14:26:48] [nodemon] watching 67 files
/www/src/app.js:1
(function (exports, require, module, __filename, __dirname) { import Koa2 from 'koa';
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Module._compile (/www/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.newLoader [as .js] (/www/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[14:26:48] [nodemon] app crashed - waiting for file changes before starting...

`

**Comment by Nebulazheng** [comment]
在服务器上运行npm run start 回 提示import 错误

**Comment by yi-ge** [comment]
线上部署，先执行`npm run build`进行编译。然后执行`npm run production`可以运行。pm2的使用参考pm2使用说明哈。

**Comment by Nebulazheng** [comment]
> 线上部署，先执行`npm run build`进行编译。然后执行`npm run production`可以运行。pm2的使用参考pm2使用说明哈。

按照你的方法执行结果还是import错误
![image](https://user-images.githubusercontent.com/30224517/78850026-b28c6200-7a48-11ea-882f-11b067befc44.png)

**Comment by yi-ge** [comment]
请提供一下node.js版本号。

**Comment by Nebulazheng** [comment]
> 请提供一下node.js版本号。

10.15.3

**Comment by yi-ge** [comment]
@Nebulazheng 与Node.js版本无关。正常情况下编译后是没有`import`的，请检查根目录中`.babelrc`文件是否存在。
